### ISSUE TITLE
Option to suppress failure on skipped suites

### ISSUE THREAD

**Issue by gersmann** [testspace-com/testspace.support#1]
We are currently having test run failures in our Github PRs, because we skip suites under certain conditions, in order to be smart about our CI servers load. We for instance skip backend tests, if there haven't been any backend changes. 

This is reported as failure by testspace to Github and makes the PRs look like specs are failing. 

It would be great to have a configuration option to ignore deviations in test count.

**Comment by munderseth** [comment]
*Invalid processing* will not be applied if the CI status indicates `success`.  If the CI run check does `fail`, the *Invalid processing* will be executed. 

There will be no configuration required.

**Comment by munderseth** [comment]
@gersmann this has been fixed now. Thanks for pointing out this use case.

**Comment by munderseth** [comment]
Missed a use-case, re-opening. Will be patched once complete in the current release.

**Comment by munderseth** [comment]
Fixed now. `Invalid` processing is **only applied** when `[CI]` check returns `failed`.
