### ISSUE TITLE
Trial signup uses prior email without ability to edit

### ISSUE THREAD

**Issue by caneridge** [testspace-com/testspace.support#10]
Steps:

1. Sign up for free Open account, when account setup is complete, log out etc.
2. In same browser, sign up for Team account (I'm using Chrome on Linux)
![image](https://user-images.githubusercontent.com/1680419/105787894-3cec7680-5f34-11eb-9361-0558756c7e38.png)
3. The dialog prompting for a domain name and email address use the email specified in (1). The email is grayed out and cannot be edited.
4. Open a different browser (Firefox) and do step (2). Email address is blank and can be edited.

Suggests that browser has saved state and this data is being used to set the email.

**Comment by caneridge** [comment]
Creating new Team account in Firefox sent email address confirmation to email account. Opening this link in Chrome produced this error: 

![image](https://user-images.githubusercontent.com/1680419/105788434-5b9f3d00-5f35-11eb-97be-ccf9fded15c5.png)

Opening the link in Firefox worked.

**Comment by caneridge** [comment]
I believe that Testspace is allowing a user to have multiple accounts and is defaulting to an existing account. Thus, when looking up the email it is not found. When logging into chrome with the Team account Testspace defaulted to my prior account and reported "Not Authorized". Once I selected my username in the upper right corner of Testspace it showed both accounts but was selecting the first account, not the account I just created and logged into. Once changed to the second account, Testspace was happy. Oddly, Testspace allowed me to see the names of both accounts when I logged into the second account but only showed one account after selecting the second account.

**Comment by ivailop** [comment]
The mix-up is related to the fact that you already had an active (in your Chrome) Testspace session. In that case, on Sign-up, as your identity is known, email editing (or any other user details) are not applicable and thus the field is grayed out. You need to end your session (by logging-out) to be able to have a fresh Sign-up... and this is why it worked as expected in your Firefox (where there was no session).

Similarly, from your email links are open in your "default" browser (your Chrome), where the already exiting **different-identity** session has no access (thus the "Not found" error) to the content of your **new** Sign-up.

**Comment by caneridge** [comment]
Please take note of the first sentence of my description above:

1. Sign up for free Open account, when account setup is complete, **log out** etc.

You have a defect in your account on-boarding.

> The mix-up is related to the fact that you already had an active (in your Chrome) Testspace session. In that case, on Sign-up, as your identity is known, email editing (or any other user details) are not applicable and thus the field is grayed out. You need to end your session (by logging-out) to be able to have a fresh Sign-up... and this is why it worked as expected in your Firefox (where there was no session).
> 
> Similarly, from your email links are open in your "default" browser (your Chrome), where the already exiting **different-identity** session has no access (thus the "Not found" error) to the content of your **new** Sign-up.
