### ISSUE TITLE
Allow onboarding users to choose their preferred GitHub email

### ISSUE THREAD

**Issue by VictorPascualV** [testspace-com/testspace.support#13]
When onboarding on TestSpace by "Sign up with Github" option, the user can't choose their preferred GitHub email to be connected to TestSpace, the "primary" GitHub email is selected by default and can not be changed during onboarding.

Once the account has been created, the email can be updated in TestSpace by "Edit Profile". The emails gets updated correctly, but after a while, probably after some "sync with GH" job runs, the emails gets reverted to the GH "Primary" email.

That's been an issue for me when onboarding, as my "Primary" GH email is my personal one, but I'd like to choose my work email as the one to be linked to TestSpace. Currently I'm getting work-related (from TestSpace) emails to my personal email, instead of to my work email.

**Comment by munderseth** [comment]
@VictorPascualV thanks for the suggestion. This enhancement should be available before the end of the month.
