### ISSUE TITLE
Testspace client support for `@`, `->`, etc. "exotic" characters in branch names

### ISSUE THREAD

**Issue by munderseth** [testspace-com/testspace.support#16]
The client is not handling branch names with unique characters. 

Reference example - https://github.com/munderseth/testspace.getting-started/tree/update/babel-eslint-%3E%40babel-eslint-parser. 

Setup erroring out - https://github.com/munderseth/testspace.getting-started/runs/2906773581?check_suite_focus=true

**Comment by munderseth** [comment]
Issue identified in this PR - https://github.com/Automattic/jetpack/pull/20085

**Comment by anomiex** [comment]
You may also want to test with non-ASCII characters such as `→` (rather than `->`), to make sure they're not being [mojibaked](https://en.wikipedia.org/wiki/Mojibake).

**Comment by munderseth** [comment]
Support for `@` in a branch name has been fixed.
