### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by aleks-ivanov** [testspace-com/testspace.support#2]
Hi, Mark :)

So here are my two questions/suggestions:

1. Is there a way to rename the badge, that is generated from each test ? It currently says "test" and I would like it to say for example "TestSpace" or "TestSpace internals" etc.

2. Is there any way currently to enable integration of the TestSpace stats and graphs, inside GitHub ? i.e. there is a label that appears on a PR and a link "details" next to it, which leads to the TestSpace website. Instead, the link to open a page inside GitHub, which to show overviews of stats and graphs, and for more details to have a link to the space inside TestSpace website.

P.S. I just found out that in the GitHub marketplace, under Actions, if I search for "testspace", nothing comes up.

**Comment by munderseth** [comment]
> 1. Is there a way to rename the badge, that is generated from each test? It currently says "test" and I would like it to say for example "TestSpace" or "TestSpace internals" etc.

We currently support the *editing* of the badge for [cutom metrics](https://help.testspace.com/docs/dashboard/space-metrics#badge).

So we are going to consider allowing this in a future release.  In addition, we are planning to add our Testspace icon to the badge. 

> 2. Is there any way currently to enable integration of the TestSpace stats and graphs, inside GitHub ? i.e. there is a label that appears on a PR and a link "details" next to it, which leads to the TestSpace website. Instead, the link to open a page inside GitHub, which to show overviews of stats and graphs, and for more details to have a link to the space inside TestSpace website.
> 

Yes, a very good suggestion and we have discussed this internally recently.  This is on our near term roadmap. 

> P.S. I just found out that in the GitHub marketplace, under Actions, if I search for "testspace", nothing comes up.

We did not add the [setup-testspace](https://github.com/testspace-com/setup-testspace) actions because it requires our GitHub app.  Do you think it would be helpful to list it?

**Comment by aleks-ivanov** [comment]
Sounds awesome! Would definitely look into the custom metrics option.

About the marketplace, my research showed that right now TestSpace is **the only** unit test visualization tool that works with GitHub Actions (apart from another action, that supports only JUnit under Ubuntu, but integrates with the GitHub interface), so I think it would be very helpful to have that availability :) First thing I did when I searched for a unit test publishing tool is go through the marketplace and only after I didn't find anything there, I commenced an extensive search through google, where I found your tool as a comment under a thread in the GitHub community section.

**Comment by munderseth** [comment]
Hi, @AleksIvanovSinglet I wanted to let you know that our next release will be supporting the GitHub [Check Run](https://github.com/testspace-com/testspace.support/issues/6), thus you can review *summary information* without going directly to Testspace.  Once we complete this will be publishing the [Testspace setup action](https://github.com/testspace-com/setup-testspace) also on the Marketplace. Also plan to make the action and app more *searchable*. 

Concerning the *Testspace badge* name, we have it internally tracked and will eventually implement this.

I am going to *close* this issue now. 

We really appreciate your feedback.

**Comment by aleks-ivanov** [comment]
My pleasure! Everything sounds great!

I wil definitely give more feedback, once I test the check run implementation :)

**Comment by munderseth** [comment]
Hi @AleksIvanovSinglet I wanted to let you know that we follow-up on your suggestion and listed the Testspace action on the Marketplace - https://github.com/marketplace/actions/testspace-setup-cli. 

We have added a few keywords to make both the App and Action more searchable.  

If you don't mind could you `Star` the action? Also, asking some of your colleges to also `Star` would be very much appreciated.

**Comment by kmura-dlb** [comment]
Hi @munderseth 
Is there any progress for the renaming of "test" in the badge? I would love to rename it to platform names. I am now adding the badges to gitlab project, but if I want status for multiple platforms it is useless, as it always says test 97% / test 98% etc.

It would be great if this badge text would be editable.

**Comment by ivailop** [comment]
@krzysztofmurawski,

As of now we decided not to allow renaming the `test` badge. 
Regarding your use case, to show multiple badges in a single page (markdown) you could easily describe them via simple document formatting, e.g.:
```
Platform-1: [test | 98%]
Platform-2: [test | 53%]
```
