### ISSUE TITLE
Doc: Incremental how link broken

### ISSUE THREAD

**Issue by caneridge** [testspace-com/testspace.support#7]
The `how` link on the bottom of this page...

https://help.testspace.com/docs/publish/push-data-results#incremental

... results in a 404 attempting to resolve:

https://help.testspace.com/docs/publish/push-data-client#url

**Comment by munderseth** [comment]
Hey thanks @caneridge, we fixed the `how` link - https://help.testspace.com/docs/reference/testspace-client#how
